spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
logging:
  level:
    com.itheima: debug
  pattern:
    dateformat: HH:mm:ss
mybatis:
  mapper-locations: classpath*:mapper/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler # 自定义枚举类型处理器
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除字段值
      logic-delete-value: 1  # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0  # 逻辑未删除值(默认为 0)
knife4j:
  enable: true
  openapi:
    title: 用户管理接口文档
    description: Spring Boot Knife4j API Document
    version: 1.0.0
    contact: zhangshen
    url: https://www.baidu.com
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.zhangshen.mybatisplus_learning.controller
